### ISSUE TITLE
Use new mlr styler package instead of styler fork for pre-commit

### ISSUE THREAD

**Issue by lorenzwalthert** [mlr-org/mlr3torch#20]
Hi 

me and @pat-s re worked the styler Stile guide for mlr. You could follow  https://github.com/mlr-org/styler.mlr/blob/main/.pre-commit-config.yaml

**Comment by sebffischer** [comment]
done in https://github.com/mlr-org/mlr3torch/commit/bc1acc60b6251a5cec81ffc8f6d0555cce2ae8c3
