### ISSUE TITLE
Transfer learning

### ISSUE THREAD

**Issue by jemus42** [mlr-org/mlr3torch#4]
Required capability esp. for image models.

Suggested API:

```r
learner$train(CIFAR10)
learner$transfer(DOGSCATS)
learner$train(DOGSCATS)
```

Where `.$transfer` needs to adjust at least the number of output nodes in the model contained in `learner`.  
Possibly required adjustments to e.g. loss function etc. could be args to `.$transfer` but those should be parameters of the learner anyway.

**Comment by pfistfl** [comment]
Could also be learner$train(transfer =TRUE)

**Comment by sebffischer** [comment]
the transfer = TRUE does not really work because we would had to: 

1. Modify mlr3's learner_train function
2. How would you specify that in a GraphLearner?
