### ISSUE TITLE
Benchmark speed

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3torch#74]
What we want to compare:

**Deep Learning Libraries**

* R: torch
* R: mlr3torch
* python: pytorch

**Dataset**: guess the corellation -> regression problem

**Device**: cpu and cuda

**Comment by cxzhang4** [comment]
TODO:

Verify that the timing strategies in Python and R are equivalent.

Verify that each framework uses the same number of cores and threads (set to 1 for simplicity)
- mlr3torch uses 1 thread by default 

run the experiments on some GPU
